package main;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class FirstTestTestTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","C:\\Users\\Berdi\\Desktop\\Selenium\\chromedriver_win32\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void firstTestTest() {
        driver.get("https://www.amazon.com/ref=nav_logo");
        driver.manage().window().setSize(new Dimension(821, 784));
        driver.findElement(By.cssSelector(".a-carousel-goto-prevpage")).click();
        driver.findElement(By.cssSelector(".hm-icon")).click();
        driver.findElement(By.cssSelector("li:nth-child(2) > .hmenu-item > div")).click();
        driver.findElement(By.linkText("Prime Video")).click();
        driver.findElement(By.id("twotabsearchtextbox")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".nav-search-submit > .nav-input"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        driver.findElement(By.id("twotabsearchtextbox")).sendKeys("stationary");
        driver.findElement(By.cssSelector(".nav-search-submit > .nav-input")).click();
        driver.close();
    }
}
